stolostron/ui-components

src/AcmButton/AcmButton.tsx, src/AcmModal/AcmModal.stories.tsx, src/AcmModal/AcmModal.test.tsx, src/AcmModal/AcmModal.tsx
Follow pattern similar to AcmButton where we can re-use the types from Patternfly to pass through props and get full feature function from the PF components.
=> AcmModal refactor

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
When there are no bulk actions for a table:
- the 2nd column is sorted by default
- clicking a column header sorts the table by the values in the column to the left of the one clicked
=> Table sorting off-by-one without bulk actions

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
This PR introduces a RowWrapper so that the `data-ouia-component-id` can be set to match the row key in our tables. This will enable easier row selection in our Cypress tests.
=> TableRow OUIA support

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
If context is not set, table defaults to using state. By wrapping tables with `AcmTablePaginationContextProvider`, page size can be saved in the browser, and different tables that are conceptually one table can have their page size change in concert.
=> Support saving perPage setting in context

src/AcmExpandableWrapper/AcmExpandableWrapper.stories.tsx, src/AcmExpandableWrapper/AcmExpandableWrapper.test.tsx, src/AcmExpandableWrapper/AcmExpandableWrapper.tsx
allows option of counter in wrapper header or show more button.
Saved search cards shows count:
<kbd>
</kbd>
Suggested does not:
<kbd>
</kbd>
=> add condition for card count visibility

src/AcmCharts/index.tsx
I'm getting this error when trying to use AcmChartGroup.  Hoping this fixes it.
```
'"../../../node_modules/@open-cluster-management/ui-components/lib"' has no exported member named 'AcmChartGroup'. Did you mean 'AcmAlertGroup'?  TS2724
1 | import { useState } from 'react'
> 2 | import { AcmChartGroup, AcmDonutChart, AcmPage, AcmPageHeader, AcmOverviewProviders, AcmSummaryList, Provider } from '@open-cluster-management/ui-components'
```
=> Add missing AcmChartGroup export

src/AcmExpandableWrapper/AcmExpandableWrapper.tsx
Gallery layout works better than Grid for saved searches and related tiles.
=> Use gallery layout for saved searches and cards

src/AcmDescriptionList/AcmDescriptionList.tsx
https://github.com/open-cluster-management/backlog/issues/7670
Right now there is no bottom spacing in the 2 columns. When the page is squished, the last item in the left col and the first item in the right col are stuck together like "Created" and "Clusters" below.
Screenshots of added spacing are shown below. 
The left column has 24px bottom spacing (RowGap value) so that the vertical spacing between the titles is even when the page is squished. 
The right column has 16px bottom spacing so that the white space around the box is the same.
Final result:
=> add bottom spacing to each column

src/AcmDescriptionList/AcmDescriptionList.tsx, src/AcmExpandable/AcmExpandableCard/AcmExpandableCard.tsx
https://github.com/open-cluster-management/backlog/issues/7670
- As discussed with @jackiwakin the AcmDescriptionList will have whitespace of 32px top & bottom and 24px on the sides.
- The previous margin-bottom under on the 2 columns has been removed. Now when the page is squished, only the left column will have the margin-bottom. This way the left column content is spaced evenly above the right column content.
=> update AcmDescriptionList styling

src/AcmTable/AcmTable.stories.tsx, src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
- make column headers not truncate or wrap by default
- support additional `transforms` and `cellTransforms`
=> Table transforms

package-lock.json, package.json, src/AcmTable/AcmTable.tsx
Prevents table from overflowing its parent box, by dynamically adjusting the `gridBreakPoint` property.
**Before:**
**After:**
**After (more narrow example):**
=> Implement dynamic grid breakpoint

src/AcmActionGroup/AcmActionGroup.stories.tsx, src/AcmDropdown/AcmDropdown.tsx
My last PR introduced a regression when editing button text style. This reverts the change. Also updates AcmDropdown in AcmAlertgroup.stories.tsx to use updated prop "isPlain"
Before (with onHover active) :
After (with onHover active) :
=> regression fix

src/AcmDropdown/AcmDropdown.test.tsx, src/AcmDropdown/AcmDropdown.tsx
Fixes spacing and button color when disabled.
Tied to User story: https://github.com/open-cluster-management/backlog/issues/7650
Before (spacing when isPlain prop is enabled):
After:
Before (color when disabled):
After:
=> Primary button disable color

src/AcmDropdown/AcmDropdown.tsx
Was able to reproduce the issue in story book...was not returning pf-background color when button switched between enabled and disabled. 
Conditional has been updated. Now transitions well.
Before:
https://user-images.githubusercontent.com/21374229/103667514-08445b00-4f44-11eb-969f-23d913b08366.mov
After:
https://user-images.githubusercontent.com/21374229/103667543-14301d00-4f44-11eb-9578-d1b93b48427e.mov
=> style regression fix

src/AcmTable/AcmTable.tsx
Allows for batch action button to be disabled via prop to AcmButton.
=> Use AcmButton for batch action in AcmTable

src/AcmSearchbar/AcmSearchbar.css, src/AcmSearchbar/AcmSearchbar.test.tsx, src/AcmSearchbar/AcmSearchbar.tsx
- Allow users to navigate through dropdown suggestions with arrow keys
- Don't allow users to enter a string when using an operator (ex: `cpu:=string`)
=> allow users to key through search suggestions using arrow keys

src/AcmSearchbar/AcmSearchbar.tsx
https://github.com/open-cluster-management/backlog/issues/8399
Fixes: `Can't submit a search when there's no matching filters. For example, can't search for: kind:abc`
=> Allow user to enter filters that dont match a suggestion option

src/AcmAlert/AcmAlert.stories.tsx, src/AcmAlert/AcmAlert.test.tsx, src/AcmAlert/AcmAlert.tsx
Allows clearing alerts based on a filter.
Example would be if you had alerts coming from two different operations.
Retrying one, you might want to clear the old alert on the retry, but only for what was retried.
=> Alert Group: Clear by filter

src/AcmSearchbar/AcmSearchbar.tsx
Fixes issue where the value being added that is NOT in the suggestions list gets added as a keyword.
=> Fix adding value that is not in suggestions list

src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx
onClick will pass an event as an argument, this is causing a problem because refetch() is getting the event and trying to use it in the graphql query.
=> Fix refetch button

src/AcmDropdown/AcmDropdown.tsx
regarding: https://github.com/open-cluster-management/backlog/issues/8474
Added logic to fill text and logo onHover.
=> fix for Primary button onHover

src/AcmLabelsInput/AcmLabelsInput.test.tsx, src/AcmLabelsInput/AcmLabelsInput.tsx
Issue:  https://github.com/open-cluster-management/backlog/issues/8950
Patternfly doesn't seem to allow us to configure adding a Backspace event on the X button to perform a click action; this PR just enables some focus behavior to get closer to that.
=> Add some keyboard handling around deleting labels

src/AcmCharts/AcmDonutChart/AcmDonutChart.stories.tsx, src/AcmCharts/AcmDonutChart/AcmDonutChart.test.tsx, src/AcmCharts/AcmDonutChart/AcmDonutChart.tsx
**Issue:** https://github.com/open-cluster-management/backlog/issues/8814
Adds an optional `link` to be added in the legend.  This will be used to link to the search page.
(Mouse was over `1 Non-compliant`.  Check link in the browsers bottom left corner.)
=> Add links to donut chart legend

src/AcmProvider/index.tsx
Updating the name used by cloud.Red Hat.com. It is used to add provider connections. Name was approved by Joy.
https://app.zenhub.com/workspaces/applifecycle-issue-tracker-5e480a1f17e47394a67447b9/issues/open-cluster-management/backlog/6592
=> update cloud.RedHat name

src/AcmSearchbar/AcmSearchbar.test.tsx, src/AcmSearchbar/AcmSearchbar.tsx
This fix skips the delete tag function when no tags are present in searchbar component
=> Skip delete tag function if there are no tags present in search bar

src/AcmCharts/AcmDonutChart/AcmDonutChart.tsx
Allow devs to specify a color scheme for Donut chart component.
Default:
With Scheme:
Donut chart prop would look like the following to change the theme (otherwise `colorScale` can be left undefined for default theme):
```
<AcmDonutChart
title="Pods"
description="Overview of pod count and status"
data={podData}
colorScale={['#E62325', '#EC7A08', '#F4C145', '#2B9AF3', '#72767B']} />
```
=> Add optional color scheme to donut chart

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Code to initially sort by first column without showing sort indicator was being applied during filtering, instead of allowing the fuse score sort order to be used.
=> Fix fuzzy sort

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
As an interim solution, this PR:
- makes sure extra controls are displayed whether bulk actions are used or not
- moves extra controls to the top right, as the only current use-case is a view switcher
- ensures extra controls display during loading and for empty tables
- ensures table actions appear for an empty table
=> Restore extra controls

src/AcmPage/AcmPage.tsx
A 1 px <Divider/> will disappear at certain browser page scaling
The fix is to use a thin or 1px border at the bottom or top of an area, and it always shows up at all scaling.
=> fix divider borders disappearing on scaling

src/AcmHeader/AcmHeader.tsx
previously checkOCPVersion was parsing the data returned by the /version api incorrectly, causing the perspective switcher to not be shown even on newer versions
=> fix kube version parse

src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.stories.tsx, src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx
Related issue: https://github.com/open-cluster-management/backlog/issues/10776
Allows for user to customize their initial refresh time interval, all interval values, as well as cookie for local storage.
=> make AutoRefreshSelect customizable

src/AcmTable/AcmTable.stories.tsx, src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Adds support for grouping table rows. In the storybook example, rows are grouped by provider, unless the provider is Other.
(Support for having a group summary row to come in a separate PR.)
=> Table grouping

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Because subItems/subRows do not exist in the `paged` variable, actions were operating on the wrong items when grouping or expandability is enabled.
=> Fix mapping of action clicks to items when grouped/expanded

src/AcmTable/AcmTable.stories.tsx, src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
- Add ability to customize the search placeholder (though the logic also prevents an empty string, which I think is okay)
- Add ability to position pagination controls below the table
(Let me know if anything is weird or wonky--this is literally my first TypeScript PR 🙂 )
=> Update table customizations

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Since the default `location` for Fuse is 0, the current `threshold`
setting limits matches to the first 30 characters of the text. As a
result, if a table cell has more than 30 characters, and a user copies
the entire text into the search, the filter will return 0 rows (when
users would expect *at least* the row they copied from).
See: https://fusejs.io/api/options.html#ignorelocation
An alternative fix would be to tweak the `location` and `threshold`
settings, or allow consumers to set them, but this is simpler for now.
Signed-off-by: Justin Kulikauskas <justin.kulikauskas@gmail.com>
Found with @dhaiducek when converting some tables in the grc-ui to the AcmTable.
=> Use ignoreLocation to search entire text

src/AcmDescriptionList/AcmDescriptionList.test.tsx, src/AcmDescriptionList/AcmDescriptionList.tsx
Found this while moving some of the GRC pages over to using the shared components. With the current behavior of the AcmDescriptionList, this happens:
In our use case, since the list will only be one half of the page, we want to force it to have only one column, like this:
Note: to get code coverage for this I had to add a new test, which admittedly doesn't do much, and doesn't actually test the number of columns the grid items get... UI testing is still new to me, so I welcome any suggestions on how to do that better.
=> Use full grid width if not given right items

package.json
Running `npm run build` twice results in duplicate assets.
After 1st run:
```
% tree lib/assets
lib/assets
├── EmptyPageIcon.png
├── Folder.png
├── IBM-Cloud.png
├── RHACM-Logo.min.svg
├── RHACM-Logo.svg
└── resource-destroyed.svg
```
After 2nd run:
```
% tree lib/assets
lib/assets
├── EmptyPageIcon.png
├── Folder.png
├── IBM-Cloud.png
├── RHACM-Logo.min.svg
├── RHACM-Logo.svg
├── assets
│   ├── EmptyPageIcon.png
│   ├── Folder.png
│   ├── IBM-Cloud.png
│   ├── RHACM-Logo.min.svg
│   ├── RHACM-Logo.svg
│   └── resource-destroyed.svg
└── resource-destroyed.svg
```
=> Idempotent build

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Currently, if the `sort` property is set on AcmTable, then clicking on the table headers will not update it automatically. The consuming component would need to also set the `setSort` property with an appropriate function.
In GRC's use of the AcmTable we want to set an initial sorting for the table, but we would rather not manage `sort` and `setSort` in all of our components (in general -- there might still be times where it is necessary).
This adds a property so that the sortBy state is still managed by AcmTable directly, but users can set an initial state easily.
See https://github.com/open-cluster-management/backlog/issues/12610
=> Add optional initialSort prop to AcmTable

src/AcmProgressTracker/AcmProgressTracker.stories.tsx, src/AcmProgressTracker/AcmProgressTracker.test.tsx, src/AcmProgressTracker/AcmProgressTracker.tsx
The current hive notification link uses an onClick to trigger a Get call for the hive pod. Rather than refactor this method, I want to use it with my status rollup. To do this, it will need to accept a callback as a prop.
=> adding callback to support hive log function

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Signed-off-by: Richie Piya <rpiyasirisilp@gmail.com>
https://github.com/open-cluster-management/backlog/issues/12961
Empty state when extra toolbar is present (for tables)
Empty state when there is no extra toolbar
=> add light variant if toolbar exists

src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.test.tsx, src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx
When refresh is disabled, this change ensures that `refetch()` is called initially, but then is not called again when the page is hidden and unhidden.
=> AcmAutoRefreshSelect: Prevent refresh when disabled and unhidden

src/AcmHeader/AcmHeader.tsx
accidentally changed this in a previous PR, this is to revert it
=> don't show switcher if kube version is too low

src/AcmTable/AcmTable.tsx
Issue: https://github.com/open-cluster-management/backlog/issues/14742
- Changed dropdown tooltip position to right
=> Change dropdown tooltip position to right

src/AcmDropdown/AcmDropdown.tsx, src/AcmTable/AcmTable.stories.tsx, src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx, src/utils.tsx
Signed-off-by: Feng Xiang <fxiang@redhat.com>
- Switched AcmTable tableDropdown to customTableAction for more extensibility and reduce code duplication
- Added option to TooltipWrapper to set the TooltipPosition
=> Refactor AcmTable dropdown to use AcmDropdown

src/AcmTable/AcmTable.test.tsx, src/AcmTable/AcmTable.tsx
Signed-off-by: Feng Xiang <fxiang@redhat.com>
- Put back customTableAction just for 2.4
Since customTableAction will be removed in 2.5, I'm not putting back the storybook changes.
=> Put back customTableAction just for 2.4

src/AcmLabels/AcmLabels.css, src/AcmLabels/AcmLabels.test.tsx, src/AcmLabels/AcmLabels.tsx
Fix for
**Labels in cluster details overlap the second column**
https://github.com/open-cluster-management/backlog/issues/16152
Support for label text trimming and ellipsis plus tooltip.
Top is the old labels, bottom is the fixed example.
=> acm labels support for long labels

src/AcmDropdown/AcmDropdown.stories.tsx, src/AcmDropdown/AcmDropdown.tsx
Signed-off-by: Feng Xiang <fxiang@redhat.com>
- Add option for users to change the alignment of items left or right
This is needed for app ui create button, as the default alignment is to the right which doesn't match the design:
=> Allow users to change the dropdown items alignment

package-lock.json, package.json
Switch to ts-loader 8.x for webpack 4.x compat
=> Fix storybook

src/AcmDropdown/AcmDropdown.stories.tsx, src/AcmDropdown/AcmDropdown.test.tsx, src/AcmDropdown/AcmDropdown.tsx
1. Replacing TooltipWrapper with DropdownItem tooltip prop
2. Changing disabled DropdownItems with tooltips to be AriaDisabled instead of Disabled, so that tooltip functionality still works.
Tests are not working at the moment.
Signed-off-by: Ella Juengst <ellajuengst@gmail.com>
=> Fixing dropdown accessibility issue by fixing disabled item tooltips

src/AcmInlineStatus/AcmInlineStatus.tsx, src/AcmTable/AcmTable.stories.tsx
To be used for status of "hot" clusters in a cluster pool. (`spec.runningCount`)
=> Add Running status
